
package domaine;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UserServices", targetNamespace = "http://domaine/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserServices {


    /**
     * 
     * @return
     *     returns java.util.List<domaine.User>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "recupererUtilisateurs", targetNamespace = "http://domaine/", className = "domaine.RecupererUtilisateurs")
    @ResponseWrapper(localName = "recupererUtilisateursResponse", targetNamespace = "http://domaine/", className = "domaine.RecupererUtilisateursResponse")
    @Action(input = "http://domaine/UserServices/recupererUtilisateursRequest", output = "http://domaine/UserServices/recupererUtilisateursResponse")
    public List<User> recupererUtilisateurs();

    /**
     * 
     * @param password
     * @param userType
     * @param userName
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ajouterUtilisateur", targetNamespace = "http://domaine/", className = "domaine.AjouterUtilisateur")
    @ResponseWrapper(localName = "ajouterUtilisateurResponse", targetNamespace = "http://domaine/", className = "domaine.AjouterUtilisateurResponse")
    @Action(input = "http://domaine/UserServices/ajouterUtilisateurRequest", output = "http://domaine/UserServices/ajouterUtilisateurResponse")
    public boolean ajouterUtilisateur(
        @WebParam(name = "userName", targetNamespace = "")
        String userName,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "userType", targetNamespace = "")
        UserType userType);

    /**
     * 
     * @param id
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "supprimerUtilisateur", targetNamespace = "http://domaine/", className = "domaine.SupprimerUtilisateur")
    @ResponseWrapper(localName = "supprimerUtilisateurResponse", targetNamespace = "http://domaine/", className = "domaine.SupprimerUtilisateurResponse")
    @Action(input = "http://domaine/UserServices/supprimerUtilisateurRequest", output = "http://domaine/UserServices/supprimerUtilisateurResponse")
    public boolean supprimerUtilisateur(
        @WebParam(name = "id", targetNamespace = "")
        int id);

    /**
     * 
     * @param password
     * @param id
     * @param userType
     * @param userName
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "modifierUtilisateur", targetNamespace = "http://domaine/", className = "domaine.ModifierUtilisateur")
    @ResponseWrapper(localName = "modifierUtilisateurResponse", targetNamespace = "http://domaine/", className = "domaine.ModifierUtilisateurResponse")
    @Action(input = "http://domaine/UserServices/modifierUtilisateurRequest", output = "http://domaine/UserServices/modifierUtilisateurResponse")
    public boolean modifierUtilisateur(
        @WebParam(name = "id", targetNamespace = "")
        int id,
        @WebParam(name = "userName", targetNamespace = "")
        String userName,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "userType", targetNamespace = "")
        UserType userType);

    /**
     * 
     * @param password
     * @param userName
     * @return
     *     returns domaine.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "seConnecter", targetNamespace = "http://domaine/", className = "domaine.SeConnecter")
    @ResponseWrapper(localName = "seConnecterResponse", targetNamespace = "http://domaine/", className = "domaine.SeConnecterResponse")
    @Action(input = "http://domaine/UserServices/seConnecterRequest", output = "http://domaine/UserServices/seConnecterResponse")
    public User seConnecter(
        @WebParam(name = "userName", targetNamespace = "")
        String userName,
        @WebParam(name = "password", targetNamespace = "")
        String password);

}
